<!DOCTYPE html>

<html>

<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">

	<title>IEEE IAS DA-IICT</title>

	<?php
	$home='';
	$about='';
	$events='';
	$achivevements='';
	$conf='active';
	$awards='';
	$dlp='';
	$join='';
	$branch='';

	?>
	
	<!-- Styles -->
	<link rel="stylesheet" href="css/prettyPhoto.css">
	<link rel="stylesheet" type="text/css" href="css/settings.css" media="screen"/>
	<link rel="stylesheet" href="css/bootstrap.css">
	<link rel="stylesheet" href="css/main.css">
	<link rel="stylesheet" href="css/jquery-ui.css">
	<link rel="stylesheet" href="css/yamm/yamm.css">
	<link rel="stylesheet" href="css/color-scheme/blue.css">
	<link rel="stylesheet" href="css/responsive.css">
	
	<!-- Base JS -->
	<script src="js/jquery-1.9.1.min.js"></script>
	<script src="js/bootstrap.min.js"></script>
	<script src="js/jquery.sticky.js"></script>
	<script src="js/stellar.js"></script>
	<script src="js/main.js"></script>
</head>

<body>

<div class="main">

	<!-- TOP BAR 
	============================================= -->
	
	<!-- END TOP BAR 
	============================================= -->

	<!-- HEADER 
	============================================= -->
	<?php
	include("nav.php");
	?>
	<!-- END HEADER 
	============================================= -->

	<!-- TITLE BAR
	============================================= -->
	<div class="b-titlebar">
		<div class="container layout">
			<!-- Bread Crumbs -->
			
			<!-- Title -->
			<h1>International Conferences</h1>
		</div>
	</div>
	<!-- END TITLE BAR
	============================================= -->

	<!-- CONTENT 
	============================================= -->
	<div class="content shortcodes">
		<div class="container layout">
			<div class="row">
				<div class="row-item col-md-12">
					

					 <div class='conflist' id='conf_105'><table class="table table-striped"><tbody><div class="nofilterresults hidden" id="noresults-105">
						
					</div><tr class="item-105"><td><div class='conf-full-item even'>
<div class='col-sm-7'><div class='conf-title'><span class='hidden'>c2016 IEEE Electrical Safety, Technical &amp; Mega Projects Workship (ESTMP)</span>2016 IEEE Electrical Safety, Technical &amp; Mega Projects Workship (ESTMP)</div><div class='conf-place'><span class='hidden' title='Canada-AB-Enoch'></span>Enoch, AB Canada</div><div class='conf-attendees'>Number of Attendees: 250</div></div><div class='col-sm-5'><div class='conf-date date-105'><span title='d1457928000-1458100800' class='hidden'></span>Mar 14, 2016 - Mar 16, 2016</div><div class='conf_sponsored c-sponsor'>Society Cosponsor</div></div></td></tr></div><tr class="item-105"><td><div class='conf-full-item odd'>
<div class='col-sm-7'><div class='conf-title'><span class='hidden'>c2016 IEEE Applied Power Electronics Conference and Exposition (APEC)</span><a href='http://www.apec-conf.org/' target='_blank'>2016 IEEE Applied Power Electronics Conference and Exposition (APEC)</a></div><div class='conf-place'><span class='hidden' title='USA-CA-Long Beach'></span>Long Beach, CA USA</div><div class='conf-attendees'>Number of Attendees: 3000</div></div><div class='col-sm-5'><div class='conf-date date-105'><span title='d1458446400-1458792000' class='hidden'></span>Mar 20, 2016 - Mar 24, 2016</div><div class='conf_sponsored c-sponsor'>Society Cosponsor</div></div></td></tr></div><tr class="item-105"><td><div class='conf-full-item even'>
<div class='col-sm-7'><div class='conf-title'><span class='hidden'>c2016 Eleventh International Conference on Ecological Vehicles and Renewable Energies (EVER)</span><a href='http://conference.evermonaco.com/' target='_blank'>2016 Eleventh International Conference on Ecological Vehicles and Renewable Energies (EVER)</a></div><div class='conf-place'><span class='hidden' title='Monaco-Monte Carlo'></span>Monte Carlo, Monaco</div><div class='conf-attendees'>Number of Attendees: 300</div></div><div class='col-sm-5'><div class='conf-date date-105'><span title='d1459915200-1460088000' class='hidden'></span>Apr 6, 2016 - Apr 8, 2016</div><div class='conf_sponsored t-sponsor'>Technical Cosponsor</div></div></td></tr></div><tr class="item-105"><td><div class='conf-full-item odd'>
<div class='col-sm-7'><div class='conf-title'><span class='hidden'>c2016 IET 8th International Conference on Power Electronics, Machines and Drives (PEMD)</span><a href='http://www.theiet.org/pemd' target='_blank'>2016 IET 8th International Conference on Power Electronics, Machines and Drives (PEMD)</a></div><div class='conf-place'><span class='hidden' title='United Kingdom-Glasgow'></span>Glasgow, United Kingdom</div><div class='conf-attendees'>Number of Attendees: 400</div></div><div class='col-sm-5'><div class='conf-date date-105'><span title='d1461038400-1461211200' class='hidden'></span>Apr 19, 2016 - Apr 21, 2016</div><div class='conf_sponsored t-sponsor'>Technical Cosponsor</div></div></td></tr></div><tr class="item-105"><td><div class='conf-full-item even'>
<div class='col-sm-7'><div class='conf-title'><span class='hidden'>c2016 IEEE/IAS 52nd Industrial and Commercial Power Systems Technical Conference (I&amp;CPS)</span><a href='http://sites.ieee.org/icps2016/' target='_blank'>2016 IEEE/IAS 52nd Industrial and Commercial Power Systems Technical Conference (I&amp;CPS)</a></div><div class='conf-place'><span class='hidden' title='USA-MI-Detroit'></span>Detroit, MI USA</div><div class='conf-attendees'>Number of Attendees: 100</div></div><div class='col-sm-5'><div class='conf-date date-105'><span title='d1462075200-1462420800' class='hidden'></span>May 1, 2016 - May 5, 2016</div><div class='conf_sponsored c-sponsor'>Society Cosponsor</div></div></td></tr></div><tr class="item-105"><td><div class='conf-full-item odd'>
<div class='col-sm-7'><div class='conf-title'><span class='hidden'>c2016 IEEE-IAS/PCA Cement Industry Technical Conference</span><a href='http://www.cementconference.org' target='_blank'>2016 IEEE-IAS/PCA Cement Industry Technical Conference</a></div><div class='conf-place'><span class='hidden' title='USA-TX-Dallas'></span>Dallas, TX USA</div><div class='conf-attendees'>Number of Attendees: 1200</div></div><div class='col-sm-5'><div class='conf-date date-105'><span title='d1463112000-1463716800' class='hidden'></span>May 13, 2016 - May 20, 2016</div><div class='conf_sponsored c-sponsor'>Society Cosponsor</div></div></td></tr></div><tr class="item-105"><td><div class='conf-full-item even'>
<div class='col-sm-7'><div class='conf-title'><span class='hidden'>c2016 IEEE Rural Electric Power Conference (REPC)</span><a href='http://ieeerepc.org/' target='_blank'>2016 IEEE Rural Electric Power Conference (REPC)</a></div><div class='conf-place'><span class='hidden' title='USA-CO-Westminster'></span>Westminster, CO USA</div><div class='conf-attendees'>Number of Attendees: 250</div><div class='conf-sub-date'><span title='abs1473652800' class='hidden'></span>Abstract Submission Date: Sep 12, 2016</div></div><div class='col-sm-5'><div class='conf-date date-105'><span title='d1463284800-1463544000' class='hidden'></span>May 15, 2016 - May 18, 2016</div><div class='conf_sponsored s-sponsor'>Society Sponsor</div></div></td></tr></div><tr class="item-105"><td><div class='conf-full-item odd'>
<div class='col-sm-7'><div class='conf-title'><span class='hidden'>c2016 IEEE Transportation Electrification Conference and Expo, Asia-Pacific (ITEC Asia-Pacific)</span><a href='http://www.itec2016busan.org' target='_blank'>2016 IEEE Transportation Electrification Conference and Expo, Asia-Pacific (ITEC Asia-Pacific)</a></div><div class='conf-place'><span class='hidden' title='Korea (South)-Busan'></span>Busan, Korea (South)</div><div class='conf-attendees'>Number of Attendees: 400</div></div><div class='col-sm-5'><div class='conf-date date-105'><span title='d1464753600-1465012800' class='hidden'></span>Jun 1, 2016 - Jun 4, 2016</div><div class='conf_sponsored c-sponsor'>Society Cosponsor</div></div></td></tr></div><tr class="item-105"><td><div class='conf-full-item even'>
<div class='col-sm-7'><div class='conf-title'><span class='hidden'>c2016 IEEE Symposium on Sensorless Control for Electrical Drives (SLED)</span><a href='http://sites.ieee.org/sled2016' target='_blank'>2016 IEEE Symposium on Sensorless Control for Electrical Drives (SLED)</a></div><div class='conf-place'><span class='hidden' title='Fiji-Nadi'></span>Nadi, Fiji</div><div class='conf-attendees'>Number of Attendees: 30</div></div><div class='col-sm-5'><div class='conf-date date-105'><span title='d1465099200-1465185600' class='hidden'></span>Jun 5, 2016 - Jun 6, 2016</div><div class='conf_sponsored s-sponsor'>Society Sponsor</div></div></td></tr></div><tr class="item-105"><td><div class='conf-full-item odd'>
<div class='col-sm-7'><div class='conf-title'><span class='hidden'>c2016 IEEE 16th International Conference on Environment and Electrical Engineering (EEEIC)</span><a href='http://eeeic.eu/' target='_blank'>2016 IEEE 16th International Conference on Environment and Electrical Engineering (EEEIC)</a></div><div class='conf-place'><span class='hidden' title='Italy'></span>Italy</div><div class='conf-attendees'>Number of Attendees: 450</div><div class='conf-sub-date'><span title='abs1458014400' class='hidden'></span>Abstract Submission Date: Mar 15, 2016</div></div><div class='col-sm-5'><div class='conf-date date-105'><span title='d1465272000-1465531200' class='hidden'></span>Jun 7, 2016 - Jun 10, 2016</div><div class='conf_sponsored t-sponsor'>Technical Cosponsor</div></div></td></tr></div><tr class="item-105"><td><div class='conf-full-item even'>
<div class='col-sm-7'><div class='conf-title'><span class='hidden'>c2016 Petroleum and Chemical Industry Conference Europe (PCIC Europe)</span><a href='http://www.pcic-europe.com' target='_blank'>2016 Petroleum and Chemical Industry Conference Europe (PCIC Europe)</a></div><div class='conf-place'><span class='hidden' title='Germany-Berlin'></span>Berlin, Germany</div><div class='conf-attendees'>Number of Attendees: 250</div></div><div class='col-sm-5'><div class='conf-date date-105'><span title='d1465876800-1466049600' class='hidden'></span>Jun 14, 2016 - Jun 16, 2016</div><div class='conf_sponsored t-sponsor'>Technical Cosponsor</div></div></td></tr></div><tr class="item-105"><td><div class='conf-full-item odd'>
<div class='col-sm-7'><div class='conf-title'><span class='hidden'>c2016 IEEE Pulp, Paper &amp; Forest Industries Conference (PPFIC)</span><a href='http://www.pulppaper.org' target='_blank'>2016 IEEE Pulp, Paper &amp; Forest Industries Conference (PPFIC)</a></div><div class='conf-place'><span class='hidden' title='USA-TX-Austin'></span>Austin, TX USA</div><div class='conf-attendees'>Number of Attendees: 200</div></div><div class='col-sm-5'><div class='conf-date date-105'><span title='d1466308800-1466654400' class='hidden'></span>Jun 19, 2016 - Jun 23, 2016</div><div class='conf_sponsored s-sponsor'>Society Sponsor</div></div></td></tr></div><tr class="item-105"><td><div class='conf-full-item even'>
<div class='col-sm-7'><div class='conf-title'><span class='hidden'>c2016 International Symposium on Power Electronics, Electrical Drives, Automation and Motion (SPEEDAM)</span><a href='http://www.speedam.org' target='_blank'>2016 International Symposium on Power Electronics, Electrical Drives, Automation and Motion (SPEEDAM)</a></div><div class='conf-place'><span class='hidden' title='Italy-Anacapri'></span>Anacapri, Italy</div><div class='conf-attendees'>Number of Attendees: 300</div></div><div class='col-sm-5'><div class='conf-date date-105'><span title='d1466568000-1466740800' class='hidden'></span>Jun 22, 2016 - Jun 24, 2016</div><div class='conf_sponsored t-sponsor'>Technical Cosponsor</div></div></td></tr></div><tr class="item-105"><td><div class='conf-full-item odd'>
<div class='col-sm-7'><div class='conf-title'><span class='hidden'>c2016 IEEE Transportation Electrification Conference and Expo (ITEC)</span><a href='http://www.itec-conf.com' target='_blank'>2016 IEEE Transportation Electrification Conference and Expo (ITEC)</a></div><div class='conf-place'><span class='hidden' title='USA-MI-Dearborn'></span>Dearborn, MI USA</div><div class='conf-attendees'>Number of Attendees: 600</div></div><div class='col-sm-5'><div class='conf-date date-105'><span title='d1466913600-1467172800' class='hidden'></span>Jun 26, 2016 - Jun 29, 2016</div><div class='conf_sponsored c-sponsor'>Society Cosponsor</div></div></td></tr></div><tr class="item-105"><td><div class='conf-full-item even'>
<div class='col-sm-7'><div class='conf-title'><span class='hidden'>c2016 8th International Conference on Electronics, Computers and Artificial Intelligence (ECAI)</span><a href='http://ecai.ro/' target='_blank'>2016 8th International Conference on Electronics, Computers and Artificial Intelligence (ECAI)</a></div><div class='conf-place'><span class='hidden' title='Romania-Ploiesti'></span>Ploiesti, Romania</div><div class='conf-attendees'>Number of Attendees: 140</div><div class='conf-sub-date'><span title='abs1462075200' class='hidden'></span>Abstract Submission Date: May 1, 2016</div></div><div class='col-sm-5'><div class='conf-date date-105'><span title='d1467259200-1467432000' class='hidden'></span>Jun 30, 2016 - Jul 2, 2016</div><div class='conf_sponsored t-sponsor'>Technical Cosponsor</div></div></td></tr></div><tr class="item-105"><td><div class='conf-full-item odd'>
<div class='col-sm-7'><div class='conf-title'><span class='hidden'>c2016 IEEE 1st International Conference on Power Electronics, Intelligent Control and Energy Systems (ICPEICES)</span><a href='http://www.icpeices2016.in' target='_blank'>2016 IEEE 1st International Conference on Power Electronics, Intelligent Control and Energy Systems (ICPEICES)</a></div><div class='conf-place'><span class='hidden' title='India-Delhi'></span>Delhi, India</div><div class='conf-attendees'>Number of Attendees: 400</div></div><div class='col-sm-5'><div class='conf-date date-105'><span title='d1467604800-1467777600' class='hidden'></span>Jul 4, 2016 - Jul 6, 2016</div><div class='conf_sponsored t-sponsor'>Technical Cosponsor</div></div></td></tr></div><tr class="item-105"><td><div class='conf-full-item even'>
<div class='col-sm-7'><div class='conf-title'><span class='hidden'>c2016 XXII International Conference on Electrical Machines (ICEM)</span><a href='http://www.icem.cc/2016' target='_blank'>2016 XXII International Conference on Electrical Machines (ICEM)</a></div><div class='conf-place'><span class='hidden' title='Switzerland-Ecublens'></span>Ecublens, Switzerland</div><div class='conf-attendees'>Number of Attendees: 600</div></div><div class='col-sm-5'><div class='conf-date date-105'><span title='d1472961600-1473220800' class='hidden'></span>Sep 4, 2016 - Sep 7, 2016</div><div class='conf_sponsored t-sponsor'>Technical Cosponsor</div></div></td></tr></div><tr class="item-105"><td><div class='conf-full-item odd'>
<div class='col-sm-7'><div class='conf-title'><span class='hidden'>c2016 IEEE Energy Conversion Congress and Exposition (ECCE)</span><a href='http://www.ieee-ecce.org' target='_blank'>2016 IEEE Energy Conversion Congress and Exposition (ECCE)</a></div><div class='conf-place'><span class='hidden' title='USA-WI-Milwaukee'></span>Milwaukee, WI USA</div><div class='conf-attendees'>Number of Attendees: 1100</div></div><div class='col-sm-5'><div class='conf-date date-105'><span title='d1474171200-1474516800' class='hidden'></span>Sep 18, 2016 - Sep 22, 2016</div><div class='conf_sponsored c-sponsor'>Society Cosponsor</div></div></td></tr></div><tr class="item-105"><td><div class='conf-full-item even'>
<div class='col-sm-7'><div class='conf-title'><span class='hidden'>c2016 IEEE Petroleum and Chemical Industry Technical Conference (PCIC 2016)</span><a href='http://www.ieee-pcic.org' target='_blank'>2016 IEEE Petroleum and Chemical Industry Technical Conference (PCIC 2016)</a></div><div class='conf-place'><span class='hidden' title='USA-PA-Philadelphia'></span>Philadelphia, PA USA</div><div class='conf-attendees'>Number of Attendees: 1100</div></div><div class='col-sm-5'><div class='conf-date date-105'><span title='d1474257600-1474430400' class='hidden'></span>Sep 19, 2016 - Sep 21, 2016</div><div class='conf_sponsored s-sponsor'>Society Sponsor</div></div></td></tr></div><tr class="item-105"><td><div class='conf-full-item odd'>
<div class='col-sm-7'><div class='conf-title'><span class='hidden'>c2016 IEEE International Power Electronics and Motion Control Conference (PEMC)</span><a href='http://www.ieee-pemc2016.org' target='_blank'>2016 IEEE International Power Electronics and Motion Control Conference (PEMC)</a></div><div class='conf-place'><span class='hidden' title='Bulgaria-Varna'></span>Varna, Bulgaria</div><div class='conf-attendees'>Number of Attendees: 450</div></div><div class='col-sm-5'><div class='conf-date date-105'><span title='d1474776000-1475208000' class='hidden'></span>Sep 25, 2016 - Sep 30, 2016</div><div class='conf_sponsored c-sponsor'>Society Cosponsor</div></div></td></tr></div><tr class="item-105"><td><div class='conf-full-item even'>
<div class='col-sm-7'><div class='conf-title'><span class='hidden'>c2016 IEEE Industry Applications Society Annual Meeting</span><a href='http://www.ewh.ieee.org/soc/ias/2016/' target='_blank'>2016 IEEE Industry Applications Society Annual Meeting</a></div><div class='conf-place'><span class='hidden' title='USA-OR-Portland'></span>Portland, OR USA</div><div class='conf-attendees'>Number of Attendees: 300</div></div><div class='col-sm-5'><div class='conf-date date-105'><span title='d1475380800-1475726400' class='hidden'></span>Oct 2, 2016 - Oct 6, 2016</div><div class='conf_sponsored s-sponsor'>Society Sponsor</div></div></td></tr></div><tr class="item-105"><td><div class='conf-full-item odd'>
<div class='col-sm-7'><div class='conf-title'><span class='hidden'>c2016 IEEE Petroleum and Chemical Industry Conference Brasil (PCIC Brasil)</span><a href='http://www.ieee.org.br/pcicbr' target='_blank'>2016 IEEE Petroleum and Chemical Industry Conference Brasil (PCIC Brasil)</a></div><div class='conf-place'><span class='hidden' title='Brazil-Rio de Janeiro'></span>Rio de Janeiro, Brazil</div><div class='conf-attendees'>Number of Attendees: 200</div></div><div class='col-sm-5'><div class='conf-date date-105'><span title='d1475467200-1475640000' class='hidden'></span>Oct 3, 2016 - Oct 5, 2016</div><div class='conf_sponsored t-sponsor'>Technical Cosponsor</div></div></td></tr></div><tr class="item-105"><td><div class='conf-full-item even'>
<div class='col-sm-7'><div class='conf-title'><span class='hidden'>c2016 57th International Scientific Conference on Power and Electrical Engineering of Riga Technical University (RTUCON)</span><a href='http://www.conference.rtu.lv/' target='_blank'>2016 57th International Scientific Conference on Power and Electrical Engineering of Riga Technical University (RTUCON)</a></div><div class='conf-place'><span class='hidden' title='Latvia-Riga'></span>Riga, Latvia</div><div class='conf-attendees'>Number of Attendees: 150</div><div class='conf-sub-date'><span title='abs1461297600' class='hidden'></span>Abstract Submission Date: Apr 22, 2016</div></div><div class='col-sm-5'><div class='conf-date date-105'><span title='d1476331200-1476417600' class='hidden'></span>Oct 13, 2016 - Oct 14, 2016</div><div class='conf_sponsored t-sponsor'>Technical Cosponsor</div></div></td></tr></div><tr class="item-105"><td><div class='conf-full-item odd'>
<div class='col-sm-7'><div class='conf-title'><span class='hidden'>c2016 International Symposium on Industrial Electronics (INDEL)</span><a href='http://www.indel.etfbl.net' target='_blank'>2016 International Symposium on Industrial Electronics (INDEL)</a></div><div class='conf-place'><span class='hidden' title='Bosnia and Herzegovina-Banja Luka'></span>Banja Luka, Bosnia and Herzegovina</div><div class='conf-attendees'>Number of Attendees: 70</div></div><div class='col-sm-5'><div class='conf-date date-105'><span title='d1478145600-1478318400' class='hidden'></span>Nov 3, 2016 - Nov 5, 2016</div><div class='conf_sponsored t-sponsor'>Technical Cosponsor</div></div></td></tr></div><tr class="item-105"><td><div class='conf-full-item even'>
<div class='col-sm-7'><div class='conf-title'><span class='hidden'>c2016 19th International Conference on Electrical Machines and Systems (ICEMS)</span><a href='http://www.icems2016.com/' target='_blank'>2016 19th International Conference on Electrical Machines and Systems (ICEMS)</a></div><div class='conf-place'><span class='hidden' title='Japan-Chiba'></span>Chiba, Japan</div><div class='conf-attendees'>Number of Attendees: 350</div></div><div class='col-sm-5'><div class='conf-date date-105'><span title='d1479013200-1479272400' class='hidden'></span>Nov 13, 2016 - Nov 16, 2016</div><div class='conf_sponsored t-sponsor'>Technical Cosponsor</div></div></td></tr></div><tr class="item-105"><td><div class='conf-full-item odd'>
<div class='col-sm-7'><div class='conf-title'><span class='hidden'>c2016 IEEE International Conference on Power Electronics, Drives and Energy Systems (PEDES)</span><a href='http://www.pedes2016.org' target='_blank'>2016 IEEE International Conference on Power Electronics, Drives and Energy Systems (PEDES)</a></div><div class='conf-place'><span class='hidden' title='India-Thiruvananthapuram'></span>Thiruvananthapuram, India</div><div class='conf-attendees'>Number of Attendees: 500</div><div class='conf-sub-date'><span title='abs1457928000' class='hidden'></span>Abstract Submission Date: Mar 14, 2016</div></div><div class='col-sm-5'><div class='conf-date date-105'><span title='d1481691600-1481950800' class='hidden'></span>Dec 14, 2016 - Dec 17, 2016</div><div class='conf_sponsored c-sponsor'>Society Cosponsor</div></div></td></tr></div><tr class="item-105"><td><div class='conf-full-item even'>
<div class='col-sm-7'><div class='conf-title'><span class='hidden'>c2017 IEEE IAS Electrical Safety Workshop (ESW)</span><a href='http://www.ewh.ieee.org/cmte/ias-esw/' target='_blank'>2017 IEEE IAS Electrical Safety Workshop (ESW)</a></div><div class='conf-place'><span class='hidden' title='USA-NV-Reno'></span>Reno, NV USA</div><div class='conf-attendees'>Number of Attendees: 400</div><div class='conf-sub-date'><span title='abs1459483200' class='hidden'></span>Abstract Submission Date: Apr 1, 2016</div></div><div class='col-sm-5'><div class='conf-date date-105'><span title='d1485579600-1486098000' class='hidden'></span>Jan 28, 2017 - Feb 3, 2017</div><div class='conf_sponsored c-sponsor'>Society Cosponsor</div></div></td></tr></div><tr class="item-105"><td><div class='conf-full-item odd'>
<div class='col-sm-7'><div class='conf-title'><span class='hidden'>c2017 IEEE Applied Power Electronics Conference and Exposition (APEC)</span><a href='http://www.apec-conf.org' target='_blank'>2017 IEEE Applied Power Electronics Conference and Exposition (APEC)</a></div><div class='conf-place'><span class='hidden' title='USA-FL-Tampa'></span>Tampa, FL USA</div><div class='conf-attendees'>Number of Attendees: 3000</div><div class='conf-sub-date'><span title='abs1468987200' class='hidden'></span>Abstract Submission Date: Jul 20, 2016</div></div><div class='col-sm-5'><div class='conf-date date-105'><span title='d1490500800-1490846400' class='hidden'></span>Mar 26, 2017 - Mar 30, 2017</div><div class='conf_sponsored c-sponsor'>Society Cosponsor</div></div></td></tr></div><tr class="item-105"><td><div class='conf-full-item even'>
<div class='col-sm-7'><div class='conf-title'><span class='hidden'>c2017 IEEE Rural Electric Power Conference (REPC)</span><a href='http://www.ieeerepc.org' target='_blank'>2017 IEEE Rural Electric Power Conference (REPC)</a></div><div class='conf-place'><span class='hidden' title='USA-OH-Columbus'></span>Columbus, OH USA</div><div class='conf-attendees'>Number of Attendees: 250</div><div class='conf-sub-date'><span title='abs1473998400' class='hidden'></span>Abstract Submission Date: Sep 16, 2016</div></div><div class='col-sm-5'><div class='conf-date date-105'><span title='d1492920000-1493179200' class='hidden'></span>Apr 23, 2017 - Apr 26, 2017</div><div class='conf_sponsored s-sponsor'>Society Sponsor</div></div></td></tr></div><tr class="item-105"><td><div class='conf-full-item odd'>
<div class='col-sm-7'><div class='conf-title'><span class='hidden'>c2017 IEEE-IAS/PCA Cement Industry Technical Conference</span><a href='http://www.cementconference.org' target='_blank'>2017 IEEE-IAS/PCA Cement Industry Technical Conference</a></div><div class='conf-place'><span class='hidden' title='Canada-AB-Calgary'></span>Calgary, AB Canada</div><div class='conf-attendees'>Number of Attendees: 900</div><div class='conf-sub-date'><span title='abs1472702400' class='hidden'></span>Abstract Submission Date: Sep 1, 2016</div></div><div class='col-sm-5'><div class='conf-date date-105'><span title='d1495080000-1495684800' class='hidden'></span>May 18, 2017 - May 25, 2017</div><div class='conf_sponsored c-sponsor'>Society Cosponsor</div></div></td></tr></div><tr class="item-105"><td><div class='conf-full-item even'>
<div class='col-sm-7'><div class='conf-title'><span class='hidden'>c2017 IEEE International Electric Machines &amp; Drives Conference (IEMDC)</span><a href='http://TBD' target='_blank'>2017 IEEE International Electric Machines &amp; Drives Conference (IEMDC)</a></div><div class='conf-place'><span class='hidden' title='USA-FL-Miami'></span>Miami, FL USA</div><div class='conf-attendees'>Number of Attendees: 450</div><div class='conf-sub-date'><span title='abs1481518800' class='hidden'></span>Abstract Submission Date: Dec 12, 2016</div></div><div class='col-sm-5'><div class='conf-date date-105'><span title='d1495339200-1495598400' class='hidden'></span>May 21, 2017 - May 24, 2017</div><div class='conf_sponsored c-sponsor'>Society Cosponsor</div></div></td></tr></div><tr class="item-105"><td><div class='conf-full-item odd'>
<div class='col-sm-7'><div class='conf-title'><span class='hidden'>c2017 IEEE Petroleum and Chemical Industry Technical Conference (PCIC 2017)</span>2017 IEEE Petroleum and Chemical Industry Technical Conference (PCIC 2017)</div><div class='conf-place'><span class='hidden' title='Canada-AB-Calgary'></span>Calgary, AB Canada</div><div class='conf-attendees'>Number of Attendees: 1300</div><div class='conf-sub-date'><span title='abs1472702400' class='hidden'></span>Abstract Submission Date: Sep 1, 2016</div></div><div class='col-sm-5'><div class='conf-date date-105'><span title='d1505620800-1505880000' class='hidden'></span>Sep 17, 2017 - Sep 20, 2017</div><div class='conf_sponsored s-sponsor'>Society Sponsor</div></div></td></tr></div><tr class="item-105"><td><div class='conf-full-item even'>
<div class='col-sm-7'><div class='conf-title'><span class='hidden'>c2017 IEEE Industry Applications Society Annual Meeting</span><a href='http://www.ewh.ieee.org/soc/ias/2017' target='_blank'>2017 IEEE Industry Applications Society Annual Meeting</a></div><div class='conf-place'><span class='hidden' title='USA-OH-Cincinnati'></span>Cincinnati, OH USA</div><div class='conf-attendees'>Number of Attendees: 300</div></div><div class='col-sm-5'><div class='conf-date date-105'><span title='d1506657600-1507176000' class='hidden'></span>Sep 29, 2017 - Oct 5, 2017</div><div class='conf_sponsored s-sponsor'>Society Sponsor</div></div></td></tr></div><tr class="item-105"><td><div class='conf-full-item odd'>
<div class='col-sm-7'><div class='conf-title'><span class='hidden'>c2017 IEEE Energy Conversion Congress and Exposition (ECCE)</span><a href='http://www.ieee-ecce.org' target='_blank'>2017 IEEE Energy Conversion Congress and Exposition (ECCE)</a></div><div class='conf-place'><span class='hidden' title='USA-OH-Cincinnatti'></span>Cincinnatti, OH USA</div><div class='conf-attendees'>Number of Attendees: 1300</div></div><div class='col-sm-5'><div class='conf-date date-105'><span title='d1506830400-1507176000' class='hidden'></span>Oct 1, 2017 - Oct 5, 2017</div><div class='conf_sponsored c-sponsor'>Society Cosponsor</div></div></td></tr></div><tr class="item-105"><td><div class='conf-full-item even'>
<div class='col-sm-7'><div class='conf-title'><span class='hidden'>c2018 IEEE Applied Power Electronics Conference and Exposition (APEC)</span><a href='http://www.apec-conf.org/' target='_blank'>2018 IEEE Applied Power Electronics Conference and Exposition (APEC)</a></div><div class='conf-place'><span class='hidden' title='USA-TX-San Antonio'></span>San Antonio, TX USA</div><div class='conf-attendees'>Number of Attendees: 3000</div><div class='conf-sub-date'><span title='abs1499400000' class='hidden'></span>Abstract Submission Date: Jul 7, 2017</div></div><div class='col-sm-5'><div class='conf-date date-105'><span title='d1520139600-1520485200' class='hidden'></span>Mar 4, 2018 - Mar 8, 2018</div><div class='conf_sponsored c-sponsor'>Society Cosponsor</div></div></td></tr></div><tr class="item-105"><td><div class='conf-full-item odd'>
<div class='col-sm-7'><div class='conf-title'><span class='hidden'>c2018 IEEE Electrical Safety, Technical and Mega Projects Workshop (ESTMP)</span><a href='http://sites.ieee.org/estmp/' target='_blank'>2018 IEEE Electrical Safety, Technical and Mega Projects Workshop (ESTMP)</a></div><div class='conf-place'><span class='hidden' title='Canada-AB-Calgary'></span>Calgary, AB Canada</div><div class='conf-attendees'>Number of Attendees: 200</div><div class='conf-sub-date'><span title='abs1505448000' class='hidden'></span>Abstract Submission Date: Sep 15, 2017</div></div><div class='col-sm-5'><div class='conf-date date-105'><span title='d1520827200-1521000000' class='hidden'></span>Mar 12, 2018 - Mar 14, 2018</div><div class='conf_sponsored c-sponsor'>Society Cosponsor</div></div></td></tr></div><tr class="item-105"><td><div class='conf-full-item even'>
<div class='col-sm-7'><div class='conf-title'><span class='hidden'>c2018 IEEE Rural Electric Power Conference (REPC)</span>2018 IEEE Rural Electric Power Conference (REPC)</div><div class='conf-place'><span class='hidden' title='USA-OK-Oklahoma City'></span>Oklahoma City, OK USA</div><div class='conf-attendees'>Number of Attendees: 250</div><div class='conf-sub-date'><span title='abs1505448000' class='hidden'></span>Abstract Submission Date: Sep 15, 2017</div></div><div class='col-sm-5'><div class='conf-date date-105'><span title='d1525579200-1525838400' class='hidden'></span>May 6, 2018 - May 9, 2018</div><div class='conf_sponsored s-sponsor'>Society Sponsor</div></div></td></tr></div><tr class="item-105"><td><div class='conf-full-item odd'>
<div class='col-sm-7'><div class='conf-title'><span class='hidden'>c2018 IEEE Petroleum and Chemical Industry Technical Conference (PCIC)</span>2018 IEEE Petroleum and Chemical Industry Technical Conference (PCIC)</div><div class='conf-place'><span class='hidden' title='USA-OH-Cincinnati'></span>Cincinnati, OH USA</div><div class='conf-attendees'>Number of Attendees: 1400</div><div class='conf-sub-date'><span title='abs1483506000' class='hidden'></span>Abstract Submission Date: Jan 4, 2017</div></div><div class='col-sm-5'><div class='conf-date date-105'><span title='d1537761600-1537934400' class='hidden'></span>Sep 24, 2018 - Sep 26, 2018</div><div class='conf_sponsored s-sponsor'>Society Sponsor</div></div></td></tr></div><tr class="item-105"><td><div class='conf-full-item even'>
<div class='col-sm-7'><div class='conf-title'><span class='hidden'>c2018 IEEE Energy Conversion Congress and Exposition (ECCE)</span><a href='http://www.ieee-ecce.org' target='_blank'>2018 IEEE Energy Conversion Congress and Exposition (ECCE)</a></div><div class='conf-place'><span class='hidden' title='USA-OR-Portland'></span>Portland, OR USA</div><div class='conf-attendees'>Number of Attendees: 1200</div><div class='conf-sub-date'><span title='abs1515992400' class='hidden'></span>Abstract Submission Date: Jan 15, 2018</div></div><div class='col-sm-5'><div class='conf-date date-105'><span title='d1539316800-1539835200' class='hidden'></span>Oct 12, 2018 - Oct 18, 2018</div><div class='conf_sponsored c-sponsor'>Society Cosponsor</div></div></td></tr></div></tbody></table></div>
</div>
</div>		</div>
	 </div>


					<div class="gap" style="height: 30px;"></div>
				</div>
				
			</div>

			
		</div>
	</div>
	<!-- END CONTENT 
	============================================= -->

	<!-- FOOTER 
	============================================= -->
	<?php
	include('footer.php');
	?>
	<!-- END FOOTER 
	============================================= -->
	
</div>
<!-- END MAIN 
============================================= -->

	</body>
</html>